added findBetween to k6-utils
grafana/jslib.k6.io pull request #30
Opened 2021-04-07 16:21 UTC by tom-miseur

This adds a simple function to k6-utils for finding a string between two strings (useful for data correlation).

2021-04-08 07:26 UTC, MStoykov commented on lib/k6-utils/1.0.0/index.js
> +function findBetween(content, left, right) {
```suggestion
export function findBetween(content, left, right) {
```

it needs to be exported in order to be usable

2021-04-08 07:26 UTC, MStoykov reviewed
can you also add a test in https://github.com/k6io/jslib.k6.io/blob/master/tests/basic.js

2021-04-08 14:59 UTC, sniku requested changes
I made one small comment, but the PR should be submitted to the project repository rather than to jslib itself. 
Please make the changes and post here: https://github.com/k6io/k6-jslib-utils :smile:

2021-04-08 14:59 UTC, sniku commented on lib/k6-utils/1.0.0/index.js
> +  if (end == -1) {
in JavaScript, it's better to use `===` for comparison like this.

2022-04-08 13:23 UTC, sniku commented
Closing this PR since the change has been merged already in a different PR.

2022-04-08 13:23 UTC, closed without merging